spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peep_it
    username: b02
    password: basement02
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect